/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package martin.viewtool.ui;

import java.io.File;
import javax.swing.JCheckBox;
import javax.swing.JTextField;
import martin.viewtool.config.PreferencesService;
import martin.viewtool.core.ValidationService;

/**
 *
 * @author cesar
 */
public class ViewToolPreferences extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewToolPreferences.class.getName());
    private PreferencesService preferencesService = new PreferencesService();

    /**
     * Creates new form ViewToolPreferences
     */
    public ViewToolPreferences() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooserDirDown = new javax.swing.JFileChooser();
        jOptionPane1 = new javax.swing.JOptionPane();
        fileChooserYt = new javax.swing.JFileChooser();
        panelMain = new javax.swing.JPanel();
        buttonDirectory = new javax.swing.JButton();
        buttonLimitDownload = new javax.swing.JButton();
        buttonDirYt = new javax.swing.JButton();
        textFieldLimDown = new javax.swing.JTextField();
        labelLimDown = new javax.swing.JLabel();
        checkBoxM3u = new javax.swing.JCheckBox();

        fileChooserDirDown.setAcceptAllFileFilterUsed(false);
        fileChooserDirDown.setCurrentDirectory(new java.io.File("C:\\Users\\cesar\\ViewToolDownloads"));
        fileChooserDirDown.setDialogTitle("Select download directory");
        fileChooserDirDown.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        fileChooserYt.setAcceptAllFileFilterUsed(false);
        fileChooserYt.setCurrentDirectory(new java.io.File("C:\\Program Files"));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Preferences");
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        panelMain.setLayout(null);

        buttonDirectory.setText("Choose a directory for to store the file downloaded");
        buttonDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDirectoryActionPerformed(evt);
            }
        });
        panelMain.add(buttonDirectory);
        buttonDirectory.setBounds(30, 30, 320, 30);

        buttonLimitDownload.setText("Limite download");
        buttonLimitDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimitDownloadActionPerformed(evt);
            }
        });
        panelMain.add(buttonLimitDownload);
        buttonLimitDownload.setBounds(270, 127, 220, 30);

        buttonDirYt.setText("Choose a directory where is \"yt-dlb.exe\"");
        buttonDirYt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDirYtActionPerformed(evt);
            }
        });
        panelMain.add(buttonDirYt);
        buttonDirYt.setBounds(40, 180, 270, 27);

        textFieldLimDown.setText("0");
        panelMain.add(textFieldLimDown);
        textFieldLimDown.setBounds(140, 126, 120, 30);

        labelLimDown.setText("Limit download: ");
        panelMain.add(labelLimDown);
        labelLimDown.setBounds(30, 130, 100, 16);

        checkBoxM3u.setText("create a .m3u for playlist");
        panelMain.add(checkBoxM3u);
        checkBoxM3u.setBounds(50, 80, 190, 30);

        getContentPane().add(panelMain);
        panelMain.setBounds(0, 0, 800, 370);

        setBounds(0, 0, 816, 561);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDirectoryActionPerformed
        int result = fileChooserDirDown.showOpenDialog(this); // si esto es un JDialog, también vale
    if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
        File selectedDir = fileChooserDirDown.getSelectedFile();
        
        preferencesService.setOutputDir(selectedDir.toPath());
        jOptionPane1.showMessageDialog(this, 
            "Selected directory:\n" + selectedDir.getAbsolutePath(),
            "Download folder", jOptionPane1.INFORMATION_MESSAGE); // o guárdalo en tu modelo
    }
    }//GEN-LAST:event_buttonDirectoryActionPerformed

    private void buttonDirYtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDirYtActionPerformed
       int result = fileChooserYt.showOpenDialog(this); // si esto es un JDialog, también vale
    if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
        File selectedDir = fileChooserYt.getSelectedFile();
        
        preferencesService.setYtDlpPath(selectedDir.toPath());
        jOptionPane1.showMessageDialog(this, 
            "Selected directory:\n" + selectedDir.getAbsolutePath(),
            "Download folder", jOptionPane1.INFORMATION_MESSAGE); // o guárdalo en tu modelo
    }
    }//GEN-LAST:event_buttonDirYtActionPerformed

    private void buttonLimitDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimitDownloadActionPerformed
        String speed = textFieldLimDown.getText();
        try{
            ValidationService.requireValidLimit(speed);
            Alerts.info(this, "La velocidad se ha guardado: "+speed);
            preferencesService.setLimitSpeed(speed);
        } catch(Exception ex){
            Alerts.showException(this, ex.getCause() != null ? ex.getCause() : ex);
            }
        
        
        
    }//GEN-LAST:event_buttonLimitDownloadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewToolPreferences().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDirYt;
    private javax.swing.JButton buttonDirectory;
    private javax.swing.JButton buttonLimitDownload;
    private javax.swing.JCheckBox checkBoxM3u;
    private javax.swing.JFileChooser fileChooserDirDown;
    private javax.swing.JFileChooser fileChooserYt;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JLabel labelLimDown;
    private javax.swing.JPanel panelMain;
    private javax.swing.JTextField textFieldLimDown;
    // End of variables declaration//GEN-END:variables

    public  boolean isM3uSelected(){
        return checkBoxM3u.isSelected();
    }

    
}
