/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package martin.viewtool.ui;

import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import martin.viewtool.config.PreferencesService;
import martin.viewtool.core.ValidationService;

/**
 *
 * @author cesar
 */
public class PanelPreferences extends javax.swing.JPanel {

    private final PreferencesService prefService = new PreferencesService();
    private final Font BOLD_FONT = new Font("Segoe UI", java.awt.Font.BOLD, 13);
    private final Font PLAIN_FONT = new Font("Segoe UI", java.awt.Font.PLAIN, 13);

    /**
     * Creates new form PanelPreferences
     */
    public PanelPreferences() {
        initComponents();
        checkBoxActionListener();
        agrupedIcon();
    }

    public ImageIcon fixedSizeIcon(String ruta, int ancho, int alto) {
        ImageIcon icono = new ImageIcon(getClass().getResource(ruta));
        Image img = icono.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
        return new ImageIcon(img);
    }

    private void agrupedIcon() {
        buttonDirYt.setIcon(fixedSizeIcon("/images/ytdlpicon.png", 40, 40));
        //buttonDirectory.setIcon(fixedSizeIcon("/images/selectfoldericon.png",30,30));
        buttonLimitDownload.setIcon(fixedSizeIcon("/images/saveicon.png", 20, 20));

    }

    public boolean isM3USelected() {
        return checkBoxM3u.isSelected();
    }

    private void checkBoxActionListener() {
        checkBoxM3u.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (checkBoxM3u.isSelected()) {
                    checkBoxM3u.setFont(BOLD_FONT);
                } else {
                    checkBoxM3u.setFont(PLAIN_FONT);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooserDirDown = new javax.swing.JFileChooser();
        fileChooserYt = new javax.swing.JFileChooser();
        panelPreferences = new javax.swing.JPanel();
        buttonDirectory = new javax.swing.JButton();
        buttonLimitDownload = new javax.swing.JButton();
        buttonDirYt = new javax.swing.JButton();
        textFieldLimDown = new javax.swing.JTextField();
        labelLimDown = new javax.swing.JLabel();
        checkBoxM3u = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        fileChooserDirDown.setAcceptAllFileFilterUsed(false);
        fileChooserDirDown.setCurrentDirectory(new java.io.File("C:\\Users\\cesar\\ViewToolDownloads"));
        fileChooserDirDown.setDialogTitle("Select download directory");
        fileChooserDirDown.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        fileChooserYt.setAcceptAllFileFilterUsed(false);
        fileChooserYt.setCurrentDirectory(new java.io.File("C:\\Program Files"));

        panelPreferences.setLayout(null);

        buttonDirectory.setBackground(new java.awt.Color(255, 255, 255));
        buttonDirectory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/selectfoldericon.png"))); // NOI18N
        buttonDirectory.setBorder(null);
        buttonDirectory.setBorderPainted(false);
        buttonDirectory.setOpaque(true);
        buttonDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDirectoryActionPerformed(evt);
            }
        });
        panelPreferences.add(buttonDirectory);
        buttonDirectory.setBounds(150, 30, 50, 36);

        buttonLimitDownload.setBackground(new java.awt.Color(255, 255, 255));
        buttonLimitDownload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/saveicon.png"))); // NOI18N
        buttonLimitDownload.setBorder(null);
        buttonLimitDownload.setBorderPainted(false);
        buttonLimitDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimitDownloadActionPerformed(evt);
            }
        });
        panelPreferences.add(buttonLimitDownload);
        buttonLimitDownload.setBounds(240, 110, 20, 20);

        buttonDirYt.setBackground(new java.awt.Color(255, 255, 255));
        buttonDirYt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ytdlpicon.png"))); // NOI18N
        buttonDirYt.setBorder(null);
        buttonDirYt.setBorderPainted(false);
        buttonDirYt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDirYtActionPerformed(evt);
            }
        });
        panelPreferences.add(buttonDirYt);
        buttonDirYt.setBounds(350, 30, 50, 40);

        textFieldLimDown.setText("0");
        panelPreferences.add(textFieldLimDown);
        textFieldLimDown.setBounds(150, 110, 80, 20);

        labelLimDown.setText("Limit download: ");
        panelPreferences.add(labelLimDown);
        labelLimDown.setBounds(50, 110, 120, 16);

        checkBoxM3u.setText("Create a .m3u for playlist");
        checkBoxM3u.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxM3uActionPerformed(evt);
            }
        });
        panelPreferences.add(checkBoxM3u);
        checkBoxM3u.setBounds(50, 170, 190, 30);

        jLabel1.setText("Select Folder :");
        panelPreferences.add(jLabel1);
        jLabel1.setBounds(50, 30, 110, 40);

        jLabel2.setText("Locate yt-dlp.exe :");
        panelPreferences.add(jLabel2);
        jLabel2.setBounds(230, 40, 120, 16);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/workicon.png"))); // NOI18N
        panelPreferences.add(jLabel3);
        jLabel3.setBounds(270, 180, 270, 250);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setText("More features coming soon...");
        panelPreferences.add(jLabel4);
        jLabel4.setBounds(270, 440, 260, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPreferences, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPreferences, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDirectoryActionPerformed
        int result = fileChooserDirDown.showOpenDialog(this);
        if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
            File selectedDir = fileChooserDirDown.getSelectedFile();

            prefService.setOutputDir(selectedDir.toPath());
            JOptionPane.showMessageDialog(this,
                    "Selected directory:\n" + selectedDir.getAbsolutePath(),
                    "Download folder", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_buttonDirectoryActionPerformed

    private void buttonLimitDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimitDownloadActionPerformed
        String speed = textFieldLimDown.getText();
        try {
            ValidationService.requireValidLimit(speed);
            prefService.setLimitSpeed(speed);
        } catch (Exception ex) {
            Alerts.showException(this, ex.getCause() != null ? ex.getCause() : ex);
        }
    }//GEN-LAST:event_buttonLimitDownloadActionPerformed

    private void buttonDirYtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDirYtActionPerformed
        int result = fileChooserYt.showOpenDialog(this);
        if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
            File selectedDir = fileChooserYt.getSelectedFile();

            prefService.setYtDlpPath(selectedDir.toPath());
            JOptionPane.showMessageDialog(this,
                    "Selected directory:\n" + selectedDir.getAbsolutePath(),
                    "Download folder", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_buttonDirYtActionPerformed

    private void checkBoxM3uActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxM3uActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxM3uActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDirYt;
    private javax.swing.JButton buttonDirectory;
    private javax.swing.JButton buttonLimitDownload;
    private javax.swing.JCheckBox checkBoxM3u;
    private javax.swing.JFileChooser fileChooserDirDown;
    private javax.swing.JFileChooser fileChooserYt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelLimDown;
    private javax.swing.JPanel panelPreferences;
    private javax.swing.JTextField textFieldLimDown;
    // End of variables declaration//GEN-END:variables
}
