/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package martin.viewtool.ui;
import java.io.IOException;
import java.nio.file.Path;
import martin.viewtool.config.PreferencesService;
import martin.viewtool.core.DownloadController;
import martin.viewtool.core.LibraryService;
import martin.viewtool.core.MediaFormat;
import martin.viewtool.core.PlayService;
import martin.viewtool.core.YtDlpService;

/**
 *
 * @author cesar
 */
public class PanelMain extends javax.swing.JPanel {
    
    private final PreferencesService prefService = new PreferencesService();
    
    private final DownloadController controller
            = new DownloadController(new YtDlpService(prefService.getYtDlpPath()));
    
    private final PlayService playService = new PlayService();
    private final PanelPreferences preferences = new PanelPreferences();
    
    private final LibraryService libraryService = new LibraryService(Path.of(prefService.getOutputDir().toString()));

    /**
     * Creates new form PanelMain
     */
    public PanelMain() {
        initComponents();
        /*
        componente1.addCustomEventListener(new CustomEventListener() {
                @Override
                public void customEventReceived(CustomEvent evt) {
                    System.out.print("Evento OK" + evt.getMediaList());
                }
            });
            componente1.setApiUrl("https://dimedianetapi9.azurewebsites.net/");
            componente1.setToken(tokenService.getToken());
            componente1.setPollingInterval(5);
            componente1.setRunning(true);
       */
        
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        buttonMP3 = new javax.swing.JRadioButton();
        buttonMP4 = new javax.swing.JRadioButton();
        textFieldURL = new javax.swing.JTextField();
        checkBoxOnlyAudio = new javax.swing.JCheckBox();
        labelUrl = new javax.swing.JLabel();
        buttonDownload = new javax.swing.JButton();
        buttonPlayVideo = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();

        buttonMP3.setText("MP3");
        buttonMP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMP3ActionPerformed(evt);
            }
        });

        buttonMP4.setSelected(true);
        buttonMP4.setText("MP4");
        buttonMP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMP4ActionPerformed(evt);
            }
        });

        textFieldURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldURLActionPerformed(evt);
            }
        });

        checkBoxOnlyAudio.setText("Only audio");

        labelUrl.setText("URL: ");

        buttonDownload.setText("Download");
        buttonDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDownloadActionPerformed(evt);
            }
        });

        buttonPlayVideo.setText("Play last video");
        buttonPlayVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlayVideoActionPerformed(evt);
            }
        });

        progressBar.setToolTipText("");
        progressBar.setName("Progress"); // NOI18N
        progressBar.setStringPainted(true);

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMainLayout.createSequentialGroup()
                                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelMainLayout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(textFieldURL, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(10, 10, 10)
                                .addComponent(checkBoxOnlyAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelMainLayout.createSequentialGroup()
                                .addComponent(buttonMP3)
                                .addGap(51, 51, 51)
                                .addComponent(buttonMP4)
                                .addGap(71, 71, 71)
                                .addComponent(buttonDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(buttonPlayVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 832, Short.MAX_VALUE))))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxOnlyAudio))
                .addGap(12, 12, 12)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonMP3)
                    .addComponent(buttonMP4)
                    .addComponent(buttonDownload)
                    .addComponent(buttonPlayVideo))
                .addGap(24, 24, 24)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1055, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonMP3ActionPerformed

    private void buttonMP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMP4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonMP4ActionPerformed

    private void textFieldURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldURLActionPerformed

    }//GEN-LAST:event_textFieldURLActionPerformed

    private void buttonDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDownloadActionPerformed

        buttonDownload.setEnabled(false);
        progressBar.setValue(0);

        new javax.swing.SwingWorker<Integer, Integer>() {
            StringBuilder log = new StringBuilder();
            volatile boolean seenAnyPercent = false;

            @Override
            protected Integer doInBackground() throws Exception {

                java.util.function.IntConsumer onPercent = pct -> publish(pct);

                controller.validateUrl(textFieldURL.getText());

                String limit = prefService.getLimitSpeed();

                controller.validateSpeed(limit);

                Alerts.info(PanelMain.this, "The download is starting, please, wait");

                return controller.startDownload(textFieldURL.getText(),
                    buttonMP3.isSelected() ? MediaFormat.MP3 : MediaFormat.MP4,
                    checkBoxOnlyAudio.isSelected(),
                    prefService.getOutputDir(),
                    log,
                    onPercent,
                    limit,
                    preferences.isM3USelected()
                );

            }

            @Override
            protected void process(java.util.List<Integer> chunks) {
                int last = chunks.get(chunks.size() - 1);
                if (!seenAnyPercent) {
                    progressBar.setIndeterminate(false);
                    seenAnyPercent = true;
                }
                progressBar.setValue(last);
            }

            @Override
            protected void done() {
                buttonDownload.setEnabled(true);
                try {
                    int exit = get();
                    if (exit == 0) {
                        Alerts.info(PanelMain.this, "Download complete.");
                        progressBar.setValue(100);
                    } else {
                        Alerts.warn(PanelMain.this, "Process finished with some error, code : " + exit);
                    }
                } catch (Exception ex) {
                    Alerts.showException(PanelMain.this, ex.getCause() != null ? ex.getCause() : ex);
                }
            }
        }.execute();
    }//GEN-LAST:event_buttonDownloadActionPerformed

    private void buttonPlayVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlayVideoActionPerformed
        try {
            playService.playLastDownloaded(prefService.getOutputDir());
        } catch (IOException ex) {
            Alerts.showException(this, ex);
        }
    }//GEN-LAST:event_buttonPlayVideoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDownload;
    private javax.swing.JRadioButton buttonMP3;
    private javax.swing.JRadioButton buttonMP4;
    private javax.swing.JButton buttonPlayVideo;
    private javax.swing.JCheckBox checkBoxOnlyAudio;
    private javax.swing.JLabel labelUrl;
    private javax.swing.JPanel panelMain;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JTextField textFieldURL;
    // End of variables declaration//GEN-END:variables
}
