/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package martin.viewtool.ui;

import MediaSyncPolling.CheckListMediaEvent;
import MediaSyncPolling.CheckListMediaListener;
import MediaSyncPolling.MediaSyncPolling;
import java.io.IOException;
import java.nio.file.Path;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import martin.viewtool.config.PreferencesService;
import martin.viewtool.core.LibraryService;
import MediaSyncPolling.Media;
import java.io.File;
import martin.viewtool.core.MediaItem;
import martin.viewtool.core.MediaLibrary;
import martin.viewtool.core.MediaTableModel;
import martin.viewtool.core.TokenService;

/**
 *
 * @author cesar
 */
public class PanelManagement extends javax.swing.JPanel {

    private final PreferencesService prefService = new PreferencesService();

    private final LibraryService libraryService = new LibraryService(Path.of(prefService.getOutputDir().toString()));
    private ViewToolApp jframe;
    private TokenService tokenService = new TokenService();
    private boolean listenerAdded = false;

    /**
     * Creates new form PanelManagement
     */
    public PanelManagement(ViewToolApp jframe) {
        this.jframe = jframe;
        initComponents();

    }

    private void columnPrefs() {
        var columnModel = tableFiles.getColumnModel();

        // Columna 0: Name
        columnModel.getColumn(0).setPreferredWidth(300);

        // Columna 1:User ID
        columnModel.getColumn(1).setPreferredWidth(12);

        // Columna 2: MIME Type
        columnModel.getColumn(2).setPreferredWidth(40);
        // Columna 3: Date
        columnModel.getColumn(3).setPreferredWidth(300);
        ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelManagement = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listFiles = new javax.swing.JList<>();
        buttonRefreshList = new javax.swing.JButton();
        comboFilter = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableFiles = new javax.swing.JTable();
        buttonRefreshTable = new javax.swing.JButton();
        textFieldFile = new javax.swing.JTextField();
        labelSearchFile = new javax.swing.JLabel();
        buttonDeleteFile = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonDownloadFile = new javax.swing.JButton();
        buttonUploadFile = new javax.swing.JButton();
        buttonOpenFile = new javax.swing.JButton();

        panelManagement.setMaximumSize(new java.awt.Dimension(1920, 1080));
        panelManagement.setMinimumSize(new java.awt.Dimension(800, 600));
        panelManagement.setName(""); // NOI18N
        panelManagement.setLayout(null);

        jScrollPane1.setViewportView(listFiles);

        panelManagement.add(jScrollPane1);
        jScrollPane1.setBounds(0, 50, 340, 360);

        buttonRefreshList.setText("Refresh list");
        buttonRefreshList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefreshListActionPerformed(evt);
            }
        });
        panelManagement.add(buttonRefreshList);
        buttonRefreshList.setBounds(0, 410, 220, 27);

        comboFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Videos", "Audios", "Others" }));
        panelManagement.add(comboFilter);
        comboFilter.setBounds(220, 410, 120, 26);

        tableFiles.setAutoCreateRowSorter(true);
        tableFiles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tableFiles);

        panelManagement.add(jScrollPane2);
        jScrollPane2.setBounds(360, 50, 900, 400);

        buttonRefreshTable.setText("Refresh table");
        buttonRefreshTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefreshTableActionPerformed(evt);
            }
        });
        panelManagement.add(buttonRefreshTable);
        buttonRefreshTable.setBounds(360, 450, 110, 27);
        panelManagement.add(textFieldFile);
        textFieldFile.setBounds(970, 20, 150, 26);

        labelSearchFile.setText("Search :");
        panelManagement.add(labelSearchFile);
        labelSearchFile.setBounds(920, 20, 60, 30);

        buttonDeleteFile.setText("Delete File");
        buttonDeleteFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteFileActionPerformed(evt);
            }
        });
        panelManagement.add(buttonDeleteFile);
        buttonDeleteFile.setBounds(640, 450, 88, 27);

        jLabel1.setText("Media downloaded by ytb-dlp:");
        panelManagement.add(jLabel1);
        jLabel1.setBounds(10, 20, 210, 30);

        jLabel2.setText("DI Media Network Library :");
        panelManagement.add(jLabel2);
        jLabel2.setBounds(410, 20, 170, 30);

        buttonDownloadFile.setText("Download File");
        buttonDownloadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDownloadFileActionPerformed(evt);
            }
        });
        panelManagement.add(buttonDownloadFile);
        buttonDownloadFile.setBounds(730, 450, 110, 27);

        buttonUploadFile.setText("Upload File");
        buttonUploadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUploadFileActionPerformed(evt);
            }
        });
        panelManagement.add(buttonUploadFile);
        buttonUploadFile.setBounds(550, 450, 93, 27);

        buttonOpenFile.setText("Open File");
        panelManagement.add(buttonOpenFile);
        buttonOpenFile.setBounds(470, 450, 90, 27);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 1560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRefreshListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefreshListActionPerformed
        try {

            String selected = (String) comboFilter.getSelectedItem();
            List<MediaItem> files = libraryService.getFilteredFiles(selected);

            DefaultListModel<String> model = new DefaultListModel<>();
            for (MediaItem file : files) {
                model.addElement(file.getName());
            }
            listFiles.setModel(model);

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_buttonRefreshListActionPerformed

    private void buttonRefreshTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefreshTableActionPerformed
        try {

            MediaSyncPolling mediaSyncPolling = jframe.getComponent();
            String token = tokenService.getToken();

            //for networkmedia source: ViewToolNetworkDownload
            mediaSyncPolling.setToken(token);
            mediaSyncPolling.setPollingInterval(5);

            if (!listenerAdded) {

                mediaSyncPolling.addCustomEventListener(new CheckListMediaListener() {
                    @Override
                    public void checkListMediaReceived(CheckListMediaEvent evt) {
                        List<Media> mediaList = evt.getMediaList();
                        martin.viewtool.core.MediaTableModel model = new martin.viewtool.core.MediaTableModel(mediaList);
                        tableFiles.setModel(model);
                        columnPrefs();

                    }
                });
                listenerAdded = true;
            }

            mediaSyncPolling.setRunning(true);

        } catch (Exception ex) {
            Alerts.error(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_buttonRefreshTableActionPerformed

    private void buttonDeleteFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteFileActionPerformed
        //MODIFICAR CODIGO
        int selectedRow = tableFiles.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a file to delete.");
            return;
        }
        int modelRow = tableFiles.convertRowIndexToModel(selectedRow);

        MediaTableModel model = (martin.viewtool.core.MediaTableModel) tableFiles.getModel();
        Media file = model.getFile(modelRow);

        boolean confirm = Alerts.confirm(this,
                "Are you sure you want to delete this file?\n" + file.mediaFileName,
                "Confirm deletion");

        if (confirm) {
            try {
                MediaLibrary library = new martin.viewtool.core.MediaLibrary(); // CORREGIR
                boolean deleted = false;

                if (deleted) {
                    JOptionPane.showMessageDialog(this, "File deleted successfully.");
                } else {
                    JOptionPane.showMessageDialog(this, "File could not be deleted.");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error deleting file: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_buttonDeleteFileActionPerformed

    private void buttonDownloadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDownloadFileActionPerformed
        MediaSyncPolling mediaSyncPolling = jframe.getComponent();
        String token = tokenService.getToken();

        Path defaultPath = Path.of(System.getProperty("user.home"), "ViewToolNetworkDownload");
        int selectedRow = tableFiles.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a file to download.");
            return;
        }
        int modelRow = tableFiles.convertRowIndexToModel(selectedRow);

        MediaTableModel model = (martin.viewtool.core.MediaTableModel) tableFiles.getModel();
        Media file = model.getFile(modelRow);
        int idMedia = file.id;

        boolean confirm = Alerts.confirm(this,
                "Are you sure you want to download this file?\n" + file.mediaFileName,
                "Confirm deletion");

        if (confirm) {
            Path destPath = defaultPath.resolve(file.mediaFileName);
            File destFile = destPath.toFile();
            try {
                mediaSyncPolling.download(idMedia, destFile, token); // CORREGIR
                boolean deleted = true;

                if (deleted) {
                    JOptionPane.showMessageDialog(this, "File downloaded successfully.");
                } else {
                    JOptionPane.showMessageDialog(this, "File could not be downloaded.");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error downloading file: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_buttonDownloadFileActionPerformed

    private void buttonUploadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUploadFileActionPerformed


    }//GEN-LAST:event_buttonUploadFileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDeleteFile;
    private javax.swing.JButton buttonDownloadFile;
    private javax.swing.JButton buttonOpenFile;
    private javax.swing.JButton buttonRefreshList;
    private javax.swing.JButton buttonRefreshTable;
    private javax.swing.JButton buttonUploadFile;
    private javax.swing.JComboBox<String> comboFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelSearchFile;
    private javax.swing.JList<String> listFiles;
    private javax.swing.JPanel panelManagement;
    private javax.swing.JTable tableFiles;
    private javax.swing.JTextField textFieldFile;
    // End of variables declaration//GEN-END:variables
}
