/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package martin.viewtool.ui;

import java.io.IOException;
import java.nio.file.Path;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import martin.viewtool.config.PreferencesService;
import martin.viewtool.core.LibraryService;
import martin.viewtool.core.MediaItem;
import martin.viewtool.core.MediaLibrary;
import martin.viewtool.core.MediaTableModel;

/**
 *
 * @author cesar
 */
public class PanelManagement extends javax.swing.JPanel {
    private final PreferencesService prefService = new PreferencesService();
    
    private final LibraryService libraryService = new LibraryService(Path.of(prefService.getOutputDir().toString()));
   
    /**
     * Creates new form PanelManagement
     */
    public PanelManagement() {
        initComponents();
    }
    
    private void columnPrefs() {
        var columnModel = tableFiles.getColumnModel();

        // Columna 0: Name
        columnModel.getColumn(0).setPreferredWidth(300);

        // Columna 1: Size (MB)
        columnModel.getColumn(1).setPreferredWidth(20);

        // Columna 2: MIME Type
        columnModel.getColumn(2).setPreferredWidth(20);
        // Columna 3: Date
        columnModel.getColumn(3).setPreferredWidth(80);
        ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelManagement = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listFiles = new javax.swing.JList<>();
        buttonRefreshList = new javax.swing.JButton();
        comboFilter = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableFiles = new javax.swing.JTable();
        buttonRefreshTable = new javax.swing.JButton();
        textFieldFile = new javax.swing.JTextField();
        labelSearchFile = new javax.swing.JLabel();
        buttonDeleteFile = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonDownloadFile = new javax.swing.JButton();
        buttonUploadFile = new javax.swing.JButton();
        buttonOpenFile = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        panelManagement.setMaximumSize(new java.awt.Dimension(1920, 1080));
        panelManagement.setMinimumSize(new java.awt.Dimension(800, 600));
        panelManagement.setName(""); // NOI18N
        panelManagement.setLayout(null);

        jScrollPane1.setViewportView(listFiles);

        panelManagement.add(jScrollPane1);
        jScrollPane1.setBounds(0, 50, 340, 360);

        buttonRefreshList.setText("Refresh list");
        buttonRefreshList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefreshListActionPerformed(evt);
            }
        });
        panelManagement.add(buttonRefreshList);
        buttonRefreshList.setBounds(0, 410, 220, 27);

        comboFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Videos", "Audios", "Others" }));
        panelManagement.add(comboFilter);
        comboFilter.setBounds(220, 410, 120, 26);

        tableFiles.setAutoCreateRowSorter(true);
        tableFiles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tableFiles);

        panelManagement.add(jScrollPane2);
        jScrollPane2.setBounds(400, 50, 850, 400);

        buttonRefreshTable.setText("Refresh table");
        buttonRefreshTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefreshTableActionPerformed(evt);
            }
        });
        panelManagement.add(buttonRefreshTable);
        buttonRefreshTable.setBounds(640, 450, 130, 27);
        panelManagement.add(textFieldFile);
        textFieldFile.setBounds(470, 450, 160, 26);

        labelSearchFile.setText("Search :");
        panelManagement.add(labelSearchFile);
        labelSearchFile.setBounds(410, 450, 60, 30);

        buttonDeleteFile.setText("Delete File");
        buttonDeleteFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteFileActionPerformed(evt);
            }
        });
        panelManagement.add(buttonDeleteFile);
        buttonDeleteFile.setBounds(660, 790, 160, 27);

        jLabel1.setText("Media downloaded by ytb-dlp:");
        panelManagement.add(jLabel1);
        jLabel1.setBounds(10, 20, 210, 30);

        jLabel2.setText("DI Media Network :");
        panelManagement.add(jLabel2);
        jLabel2.setBounds(410, 20, 220, 30);

        buttonDownloadFile.setText("Download File");
        buttonDownloadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDownloadFileActionPerformed(evt);
            }
        });
        panelManagement.add(buttonDownloadFile);
        buttonDownloadFile.setBounds(1110, 450, 140, 27);

        buttonUploadFile.setText("Upload File");
        panelManagement.add(buttonUploadFile);
        buttonUploadFile.setBounds(520, 790, 140, 27);

        buttonOpenFile.setText("Open File");
        panelManagement.add(buttonOpenFile);
        buttonOpenFile.setBounds(390, 790, 130, 27);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        panelManagement.add(jScrollPane3);
        jScrollPane3.setBounds(390, 520, 980, 260);

        jLabel3.setText("Library Local Media: ");
        panelManagement.add(jLabel3);
        jLabel3.setBounds(410, 490, 120, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelManagement, javax.swing.GroupLayout.DEFAULT_SIZE, 1407, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRefreshListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefreshListActionPerformed
        try {

            String selected = (String) comboFilter.getSelectedItem();
            List<MediaItem> files = libraryService.getFilteredFiles(selected);

            DefaultListModel<String> model = new DefaultListModel<>();
            for (MediaItem file : files) {
                model.addElement(file.getName());
            }
            listFiles.setModel(model);

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_buttonRefreshListActionPerformed

    private void buttonRefreshTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefreshTableActionPerformed
        try {
            String search = textFieldFile.getText().trim().toLowerCase();
            
            //for networkmedia source: ViewToolNetworkDownload

            java.util.List<martin.viewtool.core.MediaItem> files = libraryService.getFiles();

            if (!search.isEmpty()) {
                files = files.stream()
                .filter(file -> file.getName().toLowerCase().contains(search))
                .toList();
            }

            martin.viewtool.core.MediaTableModel model = new martin.viewtool.core.MediaTableModel(files);
            tableFiles.setModel(model);

            columnPrefs();

        } catch (Exception ex) {
            Alerts.error(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_buttonRefreshTableActionPerformed

    private void buttonDeleteFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteFileActionPerformed
        int selectedRow = tableFiles.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a file to delete.");
            return;
        }
        int modelRow = tableFiles.convertRowIndexToModel(selectedRow);

        MediaTableModel model = (martin.viewtool.core.MediaTableModel) tableFiles.getModel();
        MediaItem file = model.getFile(modelRow);

        boolean confirm = Alerts.confirm(this,
            "Are you sure you want to delete this file?\n" + file.getName(),
            "Confirm deletion");

        if (confirm) {
            try {
                MediaLibrary library = new martin.viewtool.core.MediaLibrary();
                boolean deleted = library.delete(file);

                if (deleted) {
                    JOptionPane.showMessageDialog(this, "File deleted successfully.");
                } else {
                    JOptionPane.showMessageDialog(this, "File could not be deleted.");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error deleting file: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_buttonDeleteFileActionPerformed

    private void buttonDownloadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDownloadFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDownloadFileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDeleteFile;
    private javax.swing.JButton buttonDownloadFile;
    private javax.swing.JButton buttonOpenFile;
    private javax.swing.JButton buttonRefreshList;
    private javax.swing.JButton buttonRefreshTable;
    private javax.swing.JButton buttonUploadFile;
    private javax.swing.JComboBox<String> comboFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelSearchFile;
    private javax.swing.JList<String> listFiles;
    private javax.swing.JPanel panelManagement;
    private javax.swing.JTable tableFiles;
    private javax.swing.JTextField textFieldFile;
    // End of variables declaration//GEN-END:variables
}
