/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package martin.viewtool.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.JOptionPane;
import martin.viewtool.config.PreferencesService;
import martin.viewtool.core.UIUtils;
import martin.viewtool.core.ValidationService;

/**
 *
 * @author cesar
 */
public class PanelPreferences extends javax.swing.JPanel {

    private final PreferencesService prefService = new PreferencesService();
    private final UIUtils utils = new UIUtils();
 /**
     * Creates new form PanelPreferences
     */
    public PanelPreferences() {
        initComponents();
        agrupedIcon();
        //Mostrar el valor guardado del limite de velocidad
        textFieldLimDown.setText(prefService.getLimitSpeed());
        labelLimDown.setText("Speed: (Current: "+ prefService.getLimitSpeed()+"MB)");
        checkBoxActionListener();
       
    }
    private void agrupedIcon() {
        buttonDirYt.setIcon(utils.getFixedSizeIcon("ytdlpicon.png", 40, 40));
        buttonLimitDownload.setIcon(utils.getFixedSizeIcon("saveicon.png", 21, 21));
        buttonDirectory.setIcon(utils.getFixedSizeIcon("selectfoldericon.png", 35, 30));
    }

    public boolean isM3USelected() {
        return checkBoxM3u.isSelected();
    }

    private void checkBoxActionListener() {
        checkBoxM3u.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (checkBoxM3u.isSelected()) {
                    checkBoxM3u.setFont(UIUtils.BOLD_FONT);
                } else {
                    checkBoxM3u.setFont(UIUtils.PLAIN_FONT);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooserDirDown = new javax.swing.JFileChooser();
        fileChooserYt = new javax.swing.JFileChooser();
        panelPreferences = new javax.swing.JPanel();
        buttonDirectory = new javax.swing.JButton();
        buttonLimitDownload = new javax.swing.JButton();
        buttonDirYt = new javax.swing.JButton();
        textFieldLimDown = new javax.swing.JTextField();
        labelLimDown = new javax.swing.JLabel();
        checkBoxM3u = new javax.swing.JCheckBox();
        labelSelectFolder = new javax.swing.JLabel();
        labelYtdDlp = new javax.swing.JLabel();
        labelWorkers = new javax.swing.JLabel();
        labelTextComingSoon = new javax.swing.JLabel();
        labelExtraInfo = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();

        fileChooserDirDown.setAcceptAllFileFilterUsed(false);
        fileChooserDirDown.setCurrentDirectory(new java.io.File("C:\\Users\\cesar\\ViewToolDownloads"));
        fileChooserDirDown.setDialogTitle("Select download directory");
        fileChooserDirDown.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        fileChooserYt.setAcceptAllFileFilterUsed(false);
        fileChooserYt.setCurrentDirectory(new java.io.File("C:\\Program Files"));

        panelPreferences.setLayout(null);

        buttonDirectory.setBackground(new java.awt.Color(255, 255, 255));
        buttonDirectory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/selectfoldericon.png"))); // NOI18N
        buttonDirectory.setBorder(null);
        buttonDirectory.setBorderPainted(false);
        buttonDirectory.setOpaque(true);
        buttonDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDirectoryActionPerformed(evt);
            }
        });
        panelPreferences.add(buttonDirectory);
        buttonDirectory.setBounds(150, 30, 50, 33);

        buttonLimitDownload.setBackground(new java.awt.Color(255, 255, 255));
        buttonLimitDownload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/saveicon.png"))); // NOI18N
        buttonLimitDownload.setBorder(null);
        buttonLimitDownload.setBorderPainted(false);
        buttonLimitDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimitDownloadActionPerformed(evt);
            }
        });
        panelPreferences.add(buttonLimitDownload);
        buttonLimitDownload.setBounds(300, 110, 40, 20);

        buttonDirYt.setBackground(new java.awt.Color(255, 255, 255));
        buttonDirYt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ytdlpicon.png"))); // NOI18N
        buttonDirYt.setBorder(null);
        buttonDirYt.setBorderPainted(false);
        buttonDirYt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDirYtActionPerformed(evt);
            }
        });
        panelPreferences.add(buttonDirYt);
        buttonDirYt.setBounds(350, 30, 50, 40);

        textFieldLimDown.setText("0");
        panelPreferences.add(textFieldLimDown);
        textFieldLimDown.setBounds(200, 110, 100, 20);

        labelLimDown.setText("Speed: ");
        panelPreferences.add(labelLimDown);
        labelLimDown.setBounds(40, 110, 160, 16);

        checkBoxM3u.setText("Create a .m3u for playlist");
        checkBoxM3u.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxM3uActionPerformed(evt);
            }
        });
        panelPreferences.add(checkBoxM3u);
        checkBoxM3u.setBounds(50, 210, 190, 30);

        labelSelectFolder.setText("Select Folder :");
        panelPreferences.add(labelSelectFolder);
        labelSelectFolder.setBounds(50, 30, 110, 40);

        labelYtdDlp.setText("Locate yt-dlp.exe :");
        panelPreferences.add(labelYtdDlp);
        labelYtdDlp.setBounds(230, 40, 120, 16);

        labelWorkers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/workicon.png"))); // NOI18N
        panelPreferences.add(labelWorkers);
        labelWorkers.setBounds(270, 220, 270, 250);

        labelTextComingSoon.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        labelTextComingSoon.setText("More features coming soon...");
        panelPreferences.add(labelTextComingSoon);
        labelTextComingSoon.setBounds(270, 480, 260, 50);

        labelExtraInfo.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        labelExtraInfo.setText("Set to 0 for no limit.");
        panelPreferences.add(labelExtraInfo);
        labelExtraInfo.setBounds(200, 140, 140, 16);

        infoLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        infoLabel.setText("     ");
        panelPreferences.add(infoLabel);
        infoLabel.setBounds(360, 100, 190, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPreferences, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPreferences, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDirectoryActionPerformed
        int result = fileChooserDirDown.showOpenDialog(this);
        if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
            File selectedDir = fileChooserDirDown.getSelectedFile();

            prefService.setOutputDir(selectedDir.toPath());
            JOptionPane.showMessageDialog(this,
                    "Selected directory:\n" + selectedDir.getAbsolutePath(),
                    "Download folder", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_buttonDirectoryActionPerformed

    private void buttonLimitDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimitDownloadActionPerformed
        String speed = textFieldLimDown.getText();
        try {
            ValidationService.requireValidLimit(speed);
            prefService.setLimitSpeed(speed);
            
            textFieldLimDown.setText(prefService.getLimitSpeed());
            labelLimDown.setText("Speed: (Current: "+ prefService.getLimitSpeed()+"MB)");
        } catch (Exception ex) {
           utils.showFeedback(infoLabel,"Only integer number.", true);
        }
    }//GEN-LAST:event_buttonLimitDownloadActionPerformed

    private void buttonDirYtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDirYtActionPerformed
        int result = fileChooserYt.showOpenDialog(this);
        if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
            File selectedDir = fileChooserYt.getSelectedFile();

            prefService.setYtDlpPath(selectedDir.toPath());
            JOptionPane.showMessageDialog(this,
                    "Selected directory:\n" + selectedDir.getAbsolutePath(),
                    "Download folder", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_buttonDirYtActionPerformed

    private void checkBoxM3uActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxM3uActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxM3uActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDirYt;
    private javax.swing.JButton buttonDirectory;
    private javax.swing.JButton buttonLimitDownload;
    private javax.swing.JCheckBox checkBoxM3u;
    private javax.swing.JFileChooser fileChooserDirDown;
    private javax.swing.JFileChooser fileChooserYt;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel labelExtraInfo;
    private javax.swing.JLabel labelLimDown;
    private javax.swing.JLabel labelSelectFolder;
    private javax.swing.JLabel labelTextComingSoon;
    private javax.swing.JLabel labelWorkers;
    private javax.swing.JLabel labelYtdDlp;
    private javax.swing.JPanel panelPreferences;
    private javax.swing.JTextField textFieldLimDown;
    // End of variables declaration//GEN-END:variables
}
