/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package martin.viewtool.ui;

import java.io.IOException;
import java.nio.file.Path;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import martin.viewtool.config.PreferencesService;
import martin.viewtool.core.LibraryService;
import martin.viewtool.core.MediaItem;
import martin.viewtool.core.MediaLibrary;
import martin.viewtool.core.MediaTableModel;

/**
 *
 * @author cesar
 */
public class PanelManagement extends javax.swing.JPanel {
    private final PreferencesService prefService = new PreferencesService();
    
    private final LibraryService libraryService = new LibraryService(Path.of(prefService.getOutputDir().toString()));

    /**
     * Creates new form PanelManagement
     */
    public PanelManagement() {
        initComponents();
    }
    
    private void columnPrefs() {
        var columnModel = tableFiles.getColumnModel();

        // Columna 0: Name
        columnModel.getColumn(0).setPreferredWidth(300);

        // Columna 1: Size (MB)
        columnModel.getColumn(1).setPreferredWidth(20);

        // Columna 2: MIME Type
        columnModel.getColumn(2).setPreferredWidth(20);
        // Columna 3: Date
        columnModel.getColumn(3).setPreferredWidth(80);
        ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelManagement = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listFiles = new javax.swing.JList<>();
        buttonRefreshList = new javax.swing.JButton();
        comboFilter = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableFiles = new javax.swing.JTable();
        buttonRefreshTable = new javax.swing.JButton();
        textFieldFile = new javax.swing.JTextField();
        labelSearchFile = new javax.swing.JLabel();
        buttonDeleteFile = new javax.swing.JButton();
        buttonBackMainMng = new javax.swing.JButton();

        panelManagement.setMaximumSize(new java.awt.Dimension(1920, 1080));
        panelManagement.setMinimumSize(new java.awt.Dimension(800, 600));
        panelManagement.setName(""); // NOI18N
        panelManagement.setLayout(null);

        jScrollPane1.setViewportView(listFiles);

        panelManagement.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 340, 360);

        buttonRefreshList.setText("Refresh list");
        buttonRefreshList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefreshListActionPerformed(evt);
            }
        });
        panelManagement.add(buttonRefreshList);
        buttonRefreshList.setBounds(0, 360, 220, 27);

        comboFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Videos", "Audios", "Others" }));
        panelManagement.add(comboFilter);
        comboFilter.setBounds(220, 360, 120, 26);

        tableFiles.setAutoCreateRowSorter(true);
        tableFiles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tableFiles);

        panelManagement.add(jScrollPane2);
        jScrollPane2.setBounds(390, 0, 730, 400);

        buttonRefreshTable.setText("Refresh table");
        buttonRefreshTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefreshTableActionPerformed(evt);
            }
        });
        panelManagement.add(buttonRefreshTable);
        buttonRefreshTable.setBounds(630, 400, 120, 27);
        panelManagement.add(textFieldFile);
        textFieldFile.setBounds(460, 400, 160, 26);

        labelSearchFile.setText("Search :");
        panelManagement.add(labelSearchFile);
        labelSearchFile.setBounds(400, 400, 60, 30);

        buttonDeleteFile.setText("Delete File");
        buttonDeleteFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteFileActionPerformed(evt);
            }
        });
        panelManagement.add(buttonDeleteFile);
        buttonDeleteFile.setBounds(989, 400, 130, 27);

        buttonBackMainMng.setText("Back to main window");
        buttonBackMainMng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackMainMngActionPerformed(evt);
            }
        });
        panelManagement.add(buttonBackMainMng);
        buttonBackMainMng.setBounds(260, 500, 520, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1135, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelManagement, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelManagement, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 550, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRefreshListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefreshListActionPerformed
        try {

            String selected = (String) comboFilter.getSelectedItem();
            List<MediaItem> files = libraryService.getFilteredFiles(selected);

            DefaultListModel<String> model = new DefaultListModel<>();
            for (MediaItem file : files) {
                model.addElement(file.getName());
            }
            listFiles.setModel(model);

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_buttonRefreshListActionPerformed

    private void buttonRefreshTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefreshTableActionPerformed
        try {
            String search = textFieldFile.getText().trim().toLowerCase();

            java.util.List<martin.viewtool.core.MediaItem> files = libraryService.getFiles();

            if (!search.isEmpty()) {
                files = files.stream()
                .filter(file -> file.getName().toLowerCase().contains(search))
                .toList();
            }

            martin.viewtool.core.MediaTableModel model = new martin.viewtool.core.MediaTableModel(files);
            tableFiles.setModel(model);

            columnPrefs();

        } catch (Exception ex) {
            Alerts.error(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_buttonRefreshTableActionPerformed

    private void buttonDeleteFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteFileActionPerformed
        int selectedRow = tableFiles.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a file to delete.");
            return;
        }
        int modelRow = tableFiles.convertRowIndexToModel(selectedRow);

        MediaTableModel model = (martin.viewtool.core.MediaTableModel) tableFiles.getModel();
        MediaItem file = model.getFile(modelRow);

        boolean confirm = Alerts.confirm(this,
            "Are you sure you want to delete this file?\n" + file.getName(),
            "Confirm deletion");

        if (confirm) {
            try {
                MediaLibrary library = new martin.viewtool.core.MediaLibrary();
                boolean deleted = library.delete(file);

                if (deleted) {
                    JOptionPane.showMessageDialog(this, "File deleted successfully.");
                } else {
                    JOptionPane.showMessageDialog(this, "File could not be deleted.");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error deleting file: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_buttonDeleteFileActionPerformed

    private void buttonBackMainMngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackMainMngActionPerformed
       
    }//GEN-LAST:event_buttonBackMainMngActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBackMainMng;
    private javax.swing.JButton buttonDeleteFile;
    private javax.swing.JButton buttonRefreshList;
    private javax.swing.JButton buttonRefreshTable;
    private javax.swing.JComboBox<String> comboFilter;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelSearchFile;
    private javax.swing.JList<String> listFiles;
    private javax.swing.JPanel panelManagement;
    private javax.swing.JTable tableFiles;
    private javax.swing.JTextField textFieldFile;
    // End of variables declaration//GEN-END:variables
}
