/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package martin.viewtool.ui;

import java.io.File;
import java.nio.file.Path;
import javax.swing.JOptionPane;
import martin.viewtool.config.PreferencesService;
import martin.viewtool.core.DownloadController;
import martin.viewtool.core.LibraryService;
import martin.viewtool.core.PlayService;
import martin.viewtool.core.ValidationService;
import martin.viewtool.core.YtDlpService;

/**
 *
 * @author cesar
 */
public class PanelPreferences extends javax.swing.JPanel {
     private final PreferencesService prefService = new PreferencesService();
    private final DownloadController controller
            = new DownloadController(new YtDlpService(prefService.getYtDlpPath()));
    private final PlayService playService = new PlayService();

    private final LibraryService libraryService = new LibraryService(Path.of(prefService.getOutputDir().toString()));
   

    /**
     * Creates new form PanelPreferences
     */
    public PanelPreferences() {
        initComponents();
    }
    
    public boolean isM3USelected() {
    return checkBoxM3u.isSelected();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooserDirDown = new javax.swing.JFileChooser();
        fileChooserYt = new javax.swing.JFileChooser();
        panelPreferences = new javax.swing.JPanel();
        buttonDirectory = new javax.swing.JButton();
        buttonLimitDownload = new javax.swing.JButton();
        buttonDirYt = new javax.swing.JButton();
        textFieldLimDown = new javax.swing.JTextField();
        labelLimDown = new javax.swing.JLabel();
        checkBoxM3u = new javax.swing.JCheckBox();
        buttonBackMain = new javax.swing.JButton();

        fileChooserDirDown.setAcceptAllFileFilterUsed(false);
        fileChooserDirDown.setCurrentDirectory(new java.io.File("C:\\Users\\cesar\\ViewToolDownloads"));
        fileChooserDirDown.setDialogTitle("Select download directory");
        fileChooserDirDown.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        fileChooserYt.setAcceptAllFileFilterUsed(false);
        fileChooserYt.setCurrentDirectory(new java.io.File("C:\\Program Files"));

        panelPreferences.setLayout(null);

        buttonDirectory.setText("Choose a directory for to store the file downloaded");
        buttonDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDirectoryActionPerformed(evt);
            }
        });
        panelPreferences.add(buttonDirectory);
        buttonDirectory.setBounds(30, 30, 320, 30);

        buttonLimitDownload.setText("Limite download");
        buttonLimitDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimitDownloadActionPerformed(evt);
            }
        });
        panelPreferences.add(buttonLimitDownload);
        buttonLimitDownload.setBounds(270, 127, 220, 30);

        buttonDirYt.setText("Choose a directory where is \"yt-dlb.exe\"");
        buttonDirYt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDirYtActionPerformed(evt);
            }
        });
        panelPreferences.add(buttonDirYt);
        buttonDirYt.setBounds(40, 180, 270, 27);

        textFieldLimDown.setText("0");
        panelPreferences.add(textFieldLimDown);
        textFieldLimDown.setBounds(140, 126, 120, 30);

        labelLimDown.setText("Limit download: ");
        panelPreferences.add(labelLimDown);
        labelLimDown.setBounds(30, 130, 100, 16);

        checkBoxM3u.setText("create a .m3u for playlist");
        checkBoxM3u.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxM3uActionPerformed(evt);
            }
        });
        panelPreferences.add(checkBoxM3u);
        checkBoxM3u.setBounds(50, 80, 190, 30);

        buttonBackMain.setText("Back to Main");
        buttonBackMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackMainActionPerformed(evt);
            }
        });
        panelPreferences.add(buttonBackMain);
        buttonBackMain.setBounds(30, 240, 470, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPreferences, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPreferences, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDirectoryActionPerformed
        int result = fileChooserDirDown.showOpenDialog(this);
        if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
            File selectedDir = fileChooserDirDown.getSelectedFile();

            prefService.setOutputDir(selectedDir.toPath());
            JOptionPane.showMessageDialog(this,
                "Selected directory:\n" + selectedDir.getAbsolutePath(),
                "Download folder", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_buttonDirectoryActionPerformed

    private void buttonLimitDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimitDownloadActionPerformed
        String speed = textFieldLimDown.getText();
        try {
            ValidationService.requireValidLimit(speed);
            Alerts.info(this, "You have limited the speed in: " + speed + " // Default: 0=no limit");
            prefService.setLimitSpeed(speed);
        } catch (Exception ex) {
            Alerts.showException(this, ex.getCause() != null ? ex.getCause() : ex);
        }
    }//GEN-LAST:event_buttonLimitDownloadActionPerformed

    private void buttonDirYtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDirYtActionPerformed
        int result = fileChooserYt.showOpenDialog(this);
        if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
            File selectedDir = fileChooserYt.getSelectedFile();

            prefService.setYtDlpPath(selectedDir.toPath());
            JOptionPane.showMessageDialog(this,
                "Selected directory:\n" + selectedDir.getAbsolutePath(),
                "Download folder", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_buttonDirYtActionPerformed

    private void buttonBackMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackMainActionPerformed
        
    }//GEN-LAST:event_buttonBackMainActionPerformed

    private void checkBoxM3uActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxM3uActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxM3uActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBackMain;
    private javax.swing.JButton buttonDirYt;
    private javax.swing.JButton buttonDirectory;
    private javax.swing.JButton buttonLimitDownload;
    private javax.swing.JCheckBox checkBoxM3u;
    private javax.swing.JFileChooser fileChooserDirDown;
    private javax.swing.JFileChooser fileChooserYt;
    private javax.swing.JLabel labelLimDown;
    private javax.swing.JPanel panelPreferences;
    private javax.swing.JTextField textFieldLimDown;
    // End of variables declaration//GEN-END:variables
}
