/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package martin.viewtool.ui;

import javax.swing.JPanel;

import martin.viewtool.core.TokenService;

/**
 *
 * @author cesar
 */
public class ViewToolApp extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewToolApp.class.getName());

    private final TokenService tokenService = new TokenService();
    private String token;
    private boolean loggedIn = false;

    /**
     * Creates new form ViewToolApp
     */
    public ViewToolApp() {
        initComponents();
        token = tokenService.getToken();
        if (token == null) {
            Login login = new Login(this);
            showPanel(login);

        } else {
            loggedIn = true;
            showPanel(new PanelMain());

            
        }

    }

    public boolean isLoggedIn() {
        return loggedIn;
    }

    public void setLoggedIn(boolean loggedIn) {
        this.loggedIn = loggedIn;
    }

    public void showPanel(JPanel panel) {
        this.setContentPane(panel);
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogAbout = new javax.swing.JDialog();
        TextAreaAbout = new javax.swing.JTextArea();
        jOptionPane1 = new javax.swing.JOptionPane();
        menuBarMain = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        MenuItemExit = new javax.swing.JMenuItem();
        MenuEdit = new javax.swing.JMenu();
        MenuItemPreferences = new javax.swing.JMenuItem();
        MenuHelp = new javax.swing.JMenu();
        MenuItemAbout = new javax.swing.JMenuItem();
        MenuManagement = new javax.swing.JMenu();
        MenuManagementItem = new javax.swing.JMenuItem();
        MenuLogout = new javax.swing.JMenu();
        MenuLogoutItem = new javax.swing.JMenuItem();
        menuMain = new javax.swing.JMenu();
        MenuItemMain = new javax.swing.JMenuItem();

        dialogAbout.setTitle("About");
        dialogAbout.setModal(true);
        dialogAbout.setSize(new java.awt.Dimension(300, 300));

        TextAreaAbout.setEditable(false);
        TextAreaAbout.setColumns(20);
        TextAreaAbout.setRows(5);
        TextAreaAbout.setText("Author: César Martín Pérez.\nSubject: DI - DAM 2025/2026\nDate: 27/10/2025\n\nRecourses:\n- yt-dlp\n- ffmpeg/ffprobe\n");

        javax.swing.GroupLayout dialogAboutLayout = new javax.swing.GroupLayout(dialogAbout.getContentPane());
        dialogAbout.getContentPane().setLayout(dialogAboutLayout);
        dialogAboutLayout.setHorizontalGroup(
            dialogAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogAboutLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TextAreaAbout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dialogAboutLayout.setVerticalGroup(
            dialogAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextAreaAbout, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ViewTool");
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(null);

        MenuFile.setText("File");

        MenuItemExit.setText("Exit");
        MenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemExitActionPerformed(evt);
            }
        });
        MenuFile.add(MenuItemExit);

        menuBarMain.add(MenuFile);

        MenuEdit.setText("Edit");

        MenuItemPreferences.setText("Preferences");
        MenuItemPreferences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemPreferencesActionPerformed(evt);
            }
        });
        MenuEdit.add(MenuItemPreferences);

        menuBarMain.add(MenuEdit);

        MenuHelp.setText("Help");
        MenuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuHelpActionPerformed(evt);
            }
        });

        MenuItemAbout.setText("About");
        MenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAboutActionPerformed(evt);
            }
        });
        MenuHelp.add(MenuItemAbout);

        menuBarMain.add(MenuHelp);

        MenuManagement.setText("Media Management");
        MenuManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuManagementActionPerformed(evt);
            }
        });

        MenuManagementItem.setText("Open management window");
        MenuManagementItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuManagementItemActionPerformed(evt);
            }
        });
        MenuManagement.add(MenuManagementItem);

        menuBarMain.add(MenuManagement);

        MenuLogout.setText("Logout");

        MenuLogoutItem.setText("Logout");
        MenuLogoutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLogoutItemActionPerformed(evt);
            }
        });
        MenuLogout.add(MenuLogoutItem);

        menuBarMain.add(MenuLogout);

        menuMain.setText("Main");
        menuMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMainActionPerformed(evt);
            }
        });

        MenuItemMain.setText("Back to Main");
        MenuItemMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemMainActionPerformed(evt);
            }
        });
        menuMain.add(MenuItemMain);

        menuBarMain.add(menuMain);

        setJMenuBar(menuBarMain);

        setBounds(0, 0, 1180, 749);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemExitActionPerformed
        System.exit(0); // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemExitActionPerformed

    private void MenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAboutActionPerformed
        dialogAbout.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemAboutActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void MenuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuHelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuHelpActionPerformed

    private void MenuItemPreferencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemPreferencesActionPerformed
        if (isLoggedIn()) {
            showPanel(new PanelPreferences());
        } else {
            Alerts.error(this, "Please login to continue.");
        }


    }//GEN-LAST:event_MenuItemPreferencesActionPerformed

    private void MenuManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuManagementActionPerformed

    }//GEN-LAST:event_MenuManagementActionPerformed

    private void MenuManagementItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuManagementItemActionPerformed
        if (isLoggedIn()) {
            showPanel(new PanelManagement());

        } else {
            Alerts.error(this, "Please login to continue.");
        }


    }//GEN-LAST:event_MenuManagementItemActionPerformed

    private void MenuLogoutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLogoutItemActionPerformed
        Alerts.info(ViewToolApp.this, "The logout was successfull. You will need to login again the next time.");
        showPanel(new Login(this));
        setLoggedIn(false);
        tokenService.deleteToken();

    }//GEN-LAST:event_MenuLogoutItemActionPerformed

    private void menuMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMainActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_menuMainActionPerformed

    private void MenuItemMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemMainActionPerformed
        if (isLoggedIn()) {
            showPanel(new PanelMain());

        } else {
            Alerts.error(this, "Please login to continue.");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemMainActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuEdit;
    private javax.swing.JMenu MenuFile;
    private javax.swing.JMenu MenuHelp;
    private javax.swing.JMenuItem MenuItemAbout;
    private javax.swing.JMenuItem MenuItemExit;
    private javax.swing.JMenuItem MenuItemMain;
    private javax.swing.JMenuItem MenuItemPreferences;
    private javax.swing.JMenu MenuLogout;
    private javax.swing.JMenuItem MenuLogoutItem;
    private javax.swing.JMenu MenuManagement;
    private javax.swing.JMenuItem MenuManagementItem;
    private javax.swing.JTextArea TextAreaAbout;
    private javax.swing.JDialog dialogAbout;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JMenuBar menuBarMain;
    private javax.swing.JMenu menuMain;
    // End of variables declaration//GEN-END:variables
}
