/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package martin.viewtool.ui;

import java.io.File;
import java.io.IOException;
import martin.viewtool.config.PreferencesService;
import martin.viewtool.core.DownloadController;
import martin.viewtool.core.MediaFormat;
import martin.viewtool.core.PlayService;
import martin.viewtool.core.ValidationService;
import martin.viewtool.core.YtDlpService;

/**
 *
 * @author cesar
 */
public class ViewToolApp extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewToolApp.class.getName());

    private final PreferencesService prefSvc = new PreferencesService();
    private final DownloadController controller
            = new DownloadController(new YtDlpService(prefSvc.getYtDlpPath()));
    private final PlayService playService = new PlayService();

    /**
     * Creates new form ViewToolApp
     */
    public ViewToolApp() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        dialogAbout = new javax.swing.JDialog();
        TextAreaAbout = new javax.swing.JTextArea();
        jOptionPane1 = new javax.swing.JOptionPane();
        fileChooserYt = new javax.swing.JFileChooser();
        fileChooserDirDown = new javax.swing.JFileChooser();
        panelRoot = new javax.swing.JPanel();
        panelMain = new javax.swing.JPanel();
        buttonMP3 = new javax.swing.JRadioButton();
        buttonMP4 = new javax.swing.JRadioButton();
        textFieldURL = new javax.swing.JTextField();
        checkBoxOnlyAudio = new javax.swing.JCheckBox();
        labelUrl = new javax.swing.JLabel();
        buttonDownload = new javax.swing.JButton();
        buttonPlayVideo = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        scrollPanelText = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        panelPreferences = new javax.swing.JPanel();
        buttonDirectory = new javax.swing.JButton();
        buttonLimitDownload = new javax.swing.JButton();
        buttonDirYt = new javax.swing.JButton();
        textFieldLimDown = new javax.swing.JTextField();
        labelLimDown = new javax.swing.JLabel();
        checkBoxM3u = new javax.swing.JCheckBox();
        buttonBackMain = new javax.swing.JButton();
        menuBarMain = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        MenuItemExit = new javax.swing.JMenuItem();
        MenuEdit = new javax.swing.JMenu();
        MenuItemPreferences = new javax.swing.JMenuItem();
        MenuHelp = new javax.swing.JMenu();
        MenuItemAbout = new javax.swing.JMenuItem();

        dialogAbout.setTitle("About");
        dialogAbout.setModal(true);
        dialogAbout.setSize(new java.awt.Dimension(300, 300));

        TextAreaAbout.setEditable(false);
        TextAreaAbout.setColumns(20);
        TextAreaAbout.setRows(5);
        TextAreaAbout.setText("Author: César Martín Pérez.\nSubject: DI - DAM 2025/2026\nDate: 27/10/2025\n\nRecourses:\n- yt-dlp\n- ffmpeg/ffprobe\n");

        javax.swing.GroupLayout dialogAboutLayout = new javax.swing.GroupLayout(dialogAbout.getContentPane());
        dialogAbout.getContentPane().setLayout(dialogAboutLayout);
        dialogAboutLayout.setHorizontalGroup(
            dialogAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogAboutLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TextAreaAbout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dialogAboutLayout.setVerticalGroup(
            dialogAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextAreaAbout, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        fileChooserYt.setAcceptAllFileFilterUsed(false);
        fileChooserYt.setCurrentDirectory(new java.io.File("C:\\Program Files"));

        fileChooserDirDown.setAcceptAllFileFilterUsed(false);
        fileChooserDirDown.setCurrentDirectory(new java.io.File("C:\\Users\\cesar\\ViewToolDownloads"));
        fileChooserDirDown.setDialogTitle("Select download directory");
        fileChooserDirDown.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ViewTool");
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(null);

        panelRoot.setLayout(new java.awt.CardLayout());

        buttonGroup2.add(buttonMP3);
        buttonMP3.setText("MP3");
        buttonMP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMP3ActionPerformed(evt);
            }
        });

        buttonGroup2.add(buttonMP4);
        buttonMP4.setSelected(true);
        buttonMP4.setText("MP4");
        buttonMP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMP4ActionPerformed(evt);
            }
        });

        textFieldURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldURLActionPerformed(evt);
            }
        });

        checkBoxOnlyAudio.setText("Only audio");

        labelUrl.setText("URL: ");

        buttonDownload.setText("Download");
        buttonDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDownloadActionPerformed(evt);
            }
        });

        buttonPlayVideo.setText("Play last video");
        buttonPlayVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlayVideoActionPerformed(evt);
            }
        });

        progressBar.setToolTipText("");
        progressBar.setName("Progress"); // NOI18N
        progressBar.setStringPainted(true);

        textArea.setEditable(false);
        textArea.setColumns(20);
        textArea.setRows(5);
        scrollPanelText.setViewportView(textArea);

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollPanelText, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelMainLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(textFieldURL, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addComponent(checkBoxOnlyAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addComponent(buttonMP3)
                        .addGap(51, 51, 51)
                        .addComponent(buttonMP4)
                        .addGap(71, 71, 71)
                        .addComponent(buttonDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(buttonPlayVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(886, Short.MAX_VALUE))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxOnlyAudio))
                .addGap(12, 12, 12)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonMP3)
                    .addComponent(buttonMP4)
                    .addComponent(buttonDownload)
                    .addComponent(buttonPlayVideo))
                .addGap(18, 18, 18)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrollPanelText, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        progressBar.getAccessibleContext().setAccessibleName("");

        panelRoot.add(panelMain, "MAIN");

        panelPreferences.setLayout(null);

        buttonDirectory.setText("Choose a directory for to store the file downloaded");
        buttonDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDirectoryActionPerformed(evt);
            }
        });
        panelPreferences.add(buttonDirectory);
        buttonDirectory.setBounds(30, 30, 320, 30);

        buttonLimitDownload.setText("Limite download");
        buttonLimitDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimitDownloadActionPerformed(evt);
            }
        });
        panelPreferences.add(buttonLimitDownload);
        buttonLimitDownload.setBounds(270, 127, 220, 30);

        buttonDirYt.setText("Choose a directory where is \"yt-dlb.exe\"");
        buttonDirYt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDirYtActionPerformed(evt);
            }
        });
        panelPreferences.add(buttonDirYt);
        buttonDirYt.setBounds(40, 180, 270, 27);

        textFieldLimDown.setText("0");
        panelPreferences.add(textFieldLimDown);
        textFieldLimDown.setBounds(140, 126, 120, 30);

        labelLimDown.setText("Limit download: ");
        panelPreferences.add(labelLimDown);
        labelLimDown.setBounds(30, 130, 100, 16);

        checkBoxM3u.setText("create a .m3u for playlist");
        panelPreferences.add(checkBoxM3u);
        checkBoxM3u.setBounds(50, 80, 190, 30);

        buttonBackMain.setText("Back to Main");
        buttonBackMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackMainActionPerformed(evt);
            }
        });
        panelPreferences.add(buttonBackMain);
        buttonBackMain.setBounds(30, 240, 470, 30);

        panelRoot.add(panelPreferences, "PREFS");

        getContentPane().add(panelRoot);
        panelRoot.setBounds(0, 0, 963, 512);

        MenuFile.setText("File");

        MenuItemExit.setText("Exit");
        MenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemExitActionPerformed(evt);
            }
        });
        MenuFile.add(MenuItemExit);

        menuBarMain.add(MenuFile);

        MenuEdit.setText("Edit");

        MenuItemPreferences.setText("Preferences");
        MenuItemPreferences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemPreferencesActionPerformed(evt);
            }
        });
        MenuEdit.add(MenuItemPreferences);

        menuBarMain.add(MenuEdit);

        MenuHelp.setText("Help");
        MenuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuHelpActionPerformed(evt);
            }
        });

        MenuItemAbout.setText("About");
        MenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAboutActionPerformed(evt);
            }
        });
        MenuHelp.add(MenuItemAbout);

        menuBarMain.add(MenuHelp);

        setJMenuBar(menuBarMain);

        setBounds(0, 0, 1079, 813);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemExitActionPerformed
        System.exit(0); // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemExitActionPerformed

    private void MenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAboutActionPerformed
        dialogAbout.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemAboutActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void MenuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuHelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuHelpActionPerformed

    private void MenuItemPreferencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemPreferencesActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout) panelRoot.getLayout();
        cl.show(panelRoot, "PREFS");       // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemPreferencesActionPerformed

    private void buttonDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDirectoryActionPerformed
        int result = fileChooserDirDown.showOpenDialog(this); 
        if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
            File selectedDir = fileChooserDirDown.getSelectedFile();

            prefSvc.setOutputDir(selectedDir.toPath());
            jOptionPane1.showMessageDialog(this,
                    "Selected directory:\n" + selectedDir.getAbsolutePath(),
                    "Download folder", jOptionPane1.INFORMATION_MESSAGE); 
        }
    }//GEN-LAST:event_buttonDirectoryActionPerformed

    private void buttonLimitDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimitDownloadActionPerformed
        String speed = textFieldLimDown.getText();
        try {
            ValidationService.requireValidLimit(speed);
            Alerts.info(this, "You have limited the speed in: " + speed+" // Default: 0=no limit");
            prefSvc.setLimitSpeed(speed);
        } catch (Exception ex) {
            Alerts.showException(this, ex.getCause() != null ? ex.getCause() : ex);
        }

    }//GEN-LAST:event_buttonLimitDownloadActionPerformed

    private void buttonDirYtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDirYtActionPerformed
        int result = fileChooserYt.showOpenDialog(this); 
        if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
            File selectedDir = fileChooserYt.getSelectedFile();

            prefSvc.setYtDlpPath(selectedDir.toPath());
            jOptionPane1.showMessageDialog(this,
                    "Selected directory:\n" + selectedDir.getAbsolutePath(),
                    "Download folder", jOptionPane1.INFORMATION_MESSAGE); 
        }
    }//GEN-LAST:event_buttonDirYtActionPerformed

    private void buttonPlayVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlayVideoActionPerformed
        try {
            playService.playLastDownloaded(prefSvc.getOutputDir());
        } catch (IOException ex) {
            Alerts.showException(this, ex);
        }
    }//GEN-LAST:event_buttonPlayVideoActionPerformed

    private void buttonDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDownloadActionPerformed

        buttonDownload.setEnabled(false);
        textArea.setText("");
        progressBar.setValue(0);

        new javax.swing.SwingWorker<Integer, Integer>() {
            StringBuilder log = new StringBuilder();
            volatile boolean seenAnyPercent = false;

            @Override
            protected Integer doInBackground() throws Exception {

                java.util.function.IntConsumer onPercent = pct -> publish(pct);

                controller.validateUrl(textFieldURL.getText());

                String limit = prefSvc.getLimitSpeed();

                controller.validateSpeed(limit);


                Alerts.info(ViewToolApp.this, "The download is starting, please, wait");

                return controller.startDownload(
                        textFieldURL.getText(),
                        buttonMP3.isSelected() ? MediaFormat.MP3 : MediaFormat.MP4,
                        checkBoxOnlyAudio.isSelected(),
                        prefSvc.getOutputDir(),
                        log,
                        onPercent,
                        limit,
                       checkBoxM3u.isSelected()
                );

            }

            @Override
            protected void process(java.util.List<Integer> chunks) {
                int last = chunks.get(chunks.size() - 1);
                if (!seenAnyPercent) {
                    progressBar.setIndeterminate(false);
                    seenAnyPercent = true;
                }
                progressBar.setValue(last);
            }

            @Override
            protected void done() {
                buttonDownload.setEnabled(true);
                textArea.append(log.toString());
                try {
                    int exit = get();
                    if (exit == 0) {
                        Alerts.info(ViewToolApp.this, "Download complete.");
                        progressBar.setValue(100);
                    } else {
                        Alerts.warn(ViewToolApp.this, "Process finished with some error, code : " + exit);
                    }
                } catch (Exception ex) {
                    Alerts.showException(ViewToolApp.this, ex.getCause() != null ? ex.getCause() : ex);
                }
            }
        }.execute();

    }//GEN-LAST:event_buttonDownloadActionPerformed

    private void textFieldURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldURLActionPerformed

    }//GEN-LAST:event_textFieldURLActionPerformed

    private void buttonMP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMP4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonMP4ActionPerformed

    private void buttonMP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonMP3ActionPerformed

    private void buttonBackMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackMainActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout) panelRoot.getLayout();
        cl.show(panelRoot, "MAIN");
    }//GEN-LAST:event_buttonBackMainActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuEdit;
    private javax.swing.JMenu MenuFile;
    private javax.swing.JMenu MenuHelp;
    private javax.swing.JMenuItem MenuItemAbout;
    private javax.swing.JMenuItem MenuItemExit;
    private javax.swing.JMenuItem MenuItemPreferences;
    private javax.swing.JTextArea TextAreaAbout;
    private javax.swing.JButton buttonBackMain;
    private javax.swing.JButton buttonDirYt;
    private javax.swing.JButton buttonDirectory;
    private javax.swing.JButton buttonDownload;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton buttonLimitDownload;
    private javax.swing.JRadioButton buttonMP3;
    private javax.swing.JRadioButton buttonMP4;
    private javax.swing.JButton buttonPlayVideo;
    private javax.swing.JCheckBox checkBoxM3u;
    private javax.swing.JCheckBox checkBoxOnlyAudio;
    private javax.swing.JDialog dialogAbout;
    private javax.swing.JFileChooser fileChooserDirDown;
    private javax.swing.JFileChooser fileChooserYt;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JLabel labelLimDown;
    private javax.swing.JLabel labelUrl;
    private javax.swing.JMenuBar menuBarMain;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelPreferences;
    private javax.swing.JPanel panelRoot;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JScrollPane scrollPanelText;
    private javax.swing.JTextArea textArea;
    private javax.swing.JTextField textFieldLimDown;
    private javax.swing.JTextField textFieldURL;
    // End of variables declaration//GEN-END:variables
}
